root: true
env:
  es2021: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
  ecmaVersion: 2021
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - react
settings:
  react:
    version: detect
rules:
  no-unused-var: off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: ^_
  eqeqeq:
    - error
    - always
    - "null": ignore
  prefer-const: error
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: semi
        requireLast: true
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/no-non-null-assertion": off
